version: '3.8'
services:
  api:
    build:
      context: ./
      target: dev
    volumes:
      - .:/src
    command: npm run start
    ports:
      - "8000:8000"
    environment:
      NODE_ENV: development
