name: 'Deploy'
description: 'Deploy in the k8s'
inputs:
  env: 
    description: 'Environment Name'
    required: true
  app:
    description: 'Application Name'
    required: true
  app_version:
    description: 'Application version'
    required: true
  vault_token:
    description: 'Vault Token'
    required: true
runs:
  using: "composite"
  steps:
    - run: |
        sed ""  ./.github/environments/${{ inputs.env }}.env >> $GITHUB_ENV
      shell: bash
    
    - run: |
        CONSUL_HOST=$(echo ${CONSUL_HTTP_ADDR#*//} | cut -d: -f1)
        VAULT_HOST=$(echo ${VAULT_ADDR#*//} | cut -d: -f1)
        cd configs/
        sed -i "s#<add_tag_here>#${{ inputs.app_version }}#" ${{ inputs.app }}/ops/k8s/${{ inputs.env }}/deployment.yaml
        kubectl -n omni delete configmap ${{ inputs.app }}-configmap || true
        kubectl -n omni create configmap ${{ inputs.app }}-configmap \
            --from-literal=APP_ENV=${{ inputs.env }} \
            --from-literal=CONSUL_HOST=${CONSUL_HOST} \
            --from-literal=VAULT_HOST=${VAULT_HOST} \
            --from-literal=VAULT_TOKEN=${{ inputs.vault_token }} 
        kubectl -n omni get configmap ${{ inputs.app }}-configmap -o yaml
        kubectl -n omni apply -f ${{ inputs.app }}/ops/k8s/${{ inputs.env }}
        kubectl -n omni get all | grep ${{ inputs.app }}
      shell: bash