name: 'Publish'
description: 'Publish images'
runs:
  using: "composite"
  steps:

    - run: |
        DATE=$(date -u +%Y%m%d%H%M%S)
        TAG_VERSION=$DATE
        IMAGENAME="${{ env.IMAGE_BASE_NAME }}"
        docker build --pull \
            --no-cache=true \
            --build-arg TAG_VERSION=${TAG_VERSION} \
            --build-arg BUILD_NUMBER=${{ github.run_number }} \
            --build-arg GIT_COMMIT=${{ github.sha }} \
            -t ${{ env.REGISTRY }}/${IMAGENAME}:${TAG_VERSION} .
          docker tag ${{ env.REGISTRY }}/${IMAGENAME}:${TAG_VERSION} ${{ env.REGISTRY }}/${IMAGENAME}:${{ github.run_number }}
          docker tag ${{ env.REGISTRY }}/${IMAGENAME}:${TAG_VERSION} ${{ env.REGISTRY }}/${IMAGENAME}:latest
          echo $CR_PAT | docker login ghcr.io -u $GHCR_USER --password-stdin
          docker push ${{ env.REGISTRY }}/${IMAGENAME}:${TAG_VERSION}
          docker push ${{ env.REGISTRY }}/${IMAGENAME}:${{ github.run_number }}
          docker push ${{ env.REGISTRY }}/${IMAGENAME}:latest
          docker rmi ${{ env.REGISTRY }}/${IMAGENAME}:${TAG_VERSION} --force || true
          docker rmi ${{ env.REGISTRY }}/${IMAGENAME}:${{ github.run_number }} --force  || true
          docker rmi ${{ env.REGISTRY }}/${IMAGENAME}:latest --force  || true
        
      shell: bash
