name: 'Build'
description: 'Build and upload images'
inputs:
  env: 
    description: 'Environment variables'
    required: true
runs:
  using: "composite"
  steps:
    - run: |
        DATE=$(date -u +%Y%m%d%H%M%S)
        TAG_VERSION=$DATE
        IMAGENAME="${{ env.IMAGE_BASE_NAME }}"
        docker build --pull \
          --no-cache=true \
          --build-arg TAG_VERSION=${TAG_VERSION} \
          --build-arg BUILD_NUMBER=${{ github.run_number }} \
          --build-arg GIT_COMMIT=${{ github.sha }} \
          -t ${{ env.REGISTRY }}/${IMAGENAME}:${TAG_VERSION} .
      shell: bash
