name: Deploy DEV
on: 
  workflow_dispatch:
  workflow_run:
    workflows: [Build]
    types: [completed]

jobs:

  deploy-dev:
    runs-on:  [ "self-hosted", "linux", "x64", "dev1" ]
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
        with:  
          fetch-depth: 0 
      - name: Last tag
        id: version
        run: |
          app_version="$(git describe --tags --abbrev=0)"
          echo "app_version=$app_version"  >> $GITHUB_ENV
      - name: Checkout deployments and config
        uses: actions/checkout@v2      
        with:
          repository: omni-inc/omni-apps-deployment-configs
          token: ${{ secrets.ACCESS_TOKEN }}
          path: configs

      - name: Check files
        run: |
          find ./          

      - name: Deploy K8s
        uses: ./.github/actions/deploy
        with:
          app: ${GITHUB_REPOSITORY#*/}
          env: "dev"
          app_version: ${{ env.app_version }}
          vault_token: ${{ secrets.DEV_VAULT_TOKEN }}